name: Automação de Scraper de Voos

on:
  schedule:
    # A cada 3 horas. O formato cron: "minuto hora dia-mês mês dia-semana"
    - cron: "0 */3 * * *"
  workflow_dispatch:  # Permite disparar manualmente

jobs:
  run-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # substitua por sua versão desejada

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configurar Variáveis de Ambiente
        run: echo "Configuração das variáveis"
        env:
          user: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          dbname: ${{ secrets.DBNAME }}

      - name: Executar automação
        run: python automation.py
